# Generated by Django 4.2.7 on 2023-11-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photokeepr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.AddField(
            model_name='people',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='photokeepr.user'),
            preserve_default=False,
        ),
    ]
