# Generated by Django 4.2.7 on 2023-11-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photokeepr', '0003_alter_people_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
