# Generated by Django 4.2.7 on 2023-11-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photokeepr', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
