# Generated by Django 4.2.7 on 2023-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photokeepr', '0005_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comment',
            field=models.TextField(default='No comments'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
