# Generated by Django 4.2.7 on 2023-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photokeepr', '0006_photo_comment_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rel_photo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='photokeepr.photo')),
                ('rel_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='photokeepr.user')),
            ],
        ),
    ]
